databases:
  - name: qrgen59
    databaseName: qrgen59
    user: qrgen59

services:
  - type: web
    name: team-59_qrgen
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn QRGenProject.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: qrgen59
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4